"""Repository interface — implemented by PostgresRepo (production) and
MemoryRepo (unit tests only). The engine and routes program against this
interface so tests never touch PostgreSQL and production never touches
in-memory legal data."""
from __future__ import annotations

from typing import Any, Protocol


class Repo(Protocol):
    kind: str

    # -- legal configuration (read-only at runtime) --
    def active_rule_versions(self, as_of: str) -> list[dict[str, Any]]: ...
    def applicability_for(self, rule_version_id: str) -> list[dict[str, Any]]: ...
    def checks_for(self, rule_version_id: str) -> list[dict[str, Any]]: ...
    def list_checks(self) -> list[dict[str, Any]]: ...
    def rule_detail(self, check_id: str) -> dict[str, Any] | None: ...
    def scoring_policy(self, code: str) -> dict[str, Any] | None: ...

    # -- operational writes --
    def create_inspection(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def get_inspection(self, inspection_id: str) -> dict[str, Any] | None: ...
    def list_inspections(self) -> list[dict[str, Any]]: ...
    def add_product(self, inspection_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def get_product(self, product_id: str) -> dict[str, Any] | None: ...
    def products_for(self, inspection_id: str) -> list[dict[str, Any]]: ...
    def declarations_for(self, product_id: str) -> list[dict[str, Any]]: ...
    def save_result(self, row: dict[str, Any]) -> dict[str, Any]: ...
    def results_for(self, inspection_id: str,
                    product_id: str | None = None) -> list[dict[str, Any]]: ...
    def create_violation(self, row: dict[str, Any]) -> dict[str, Any]: ...
    def violations_for(self, inspection_id: str) -> list[dict[str, Any]]: ...
    def verify_violation(self, violation_id: str, status: str,
                         inspector_id: str = "",
                         remarks: str = "") -> dict[str, Any] | None: ...
    def audit(self, actor: str, action: str, entity: str,
              entity_id: str, detail: dict[str, Any] | None = None) -> None: ...
