"""Repository interface — implemented by PostgresRepo (production) and
MemoryRepo (unit tests only). The engine and routes program against this
interface so tests never touch PostgreSQL and production never touches
in-memory legal data."""
from __future__ import annotations

from typing import Any, Protocol


class Repo(Protocol):
    kind: str

    # -- legal configuration (read-only at runtime) --
    def active_rule_versions(self, as_of: str) -> list[dict[str, Any]]: ...
    def applicability_for(self, rule_version_id: str) -> list[dict[str, Any]]: ...
    def checks_for(self, rule_version_id: str) -> list[dict[str, Any]]: ...
    def list_checks(self) -> list[dict[str, Any]]: ...
    def rule_detail(self, check_id: str) -> dict[str, Any] | None: ...
    def scoring_policy(self, code: str) -> dict[str, Any] | None: ...

    # -- operational writes --
    def create_inspection(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def get_inspection(self, inspection_id: str) -> dict[str, Any] | None: ...
    def list_inspections(self) -> list[dict[str, Any]]: ...
    def add_product(self, inspection_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    def get_product(self, product_id: str) -> dict[str, Any] | None: ...
    def products_for(self, inspection_id: str) -> list[dict[str, Any]]: ...
    def declarations_for(self, product_id: str) -> list[dict[str, Any]]: ...
    def save_result(self, row: dict[str, Any]) -> dict[str, Any]: ...
    def results_for(self, inspection_id: str,
                    product_id: str | None = None) -> list[dict[str, Any]]: ...
    def create_violation(self, row: dict[str, Any]) -> dict[str, Any]: ...
    def get_violation(self, violation_id: str) -> dict[str, Any] | None: ...
    def violations_for(self, inspection_id: str) -> list[dict[str, Any]]: ...
    def verify_violation(self, violation_id: str, status: str,
                         inspector_id: str = "",
                         remarks: str = "") -> dict[str, Any] | None: ...
    def audit(self, actor: str, action: str, entity: str,
              entity_id: str, detail: dict[str, Any] | None = None) -> None: ...
    def audit_list(self, entity: str, entity_id: str) -> list[dict[str, Any]]: ...

    # -- consumer complaints (migration 001) --
    def create_complaint(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def get_complaint(self, complaint_id: str) -> dict[str, Any] | None: ...
    def list_complaints(self, reporter_id: str | None = None) -> list[dict[str, Any]]: ...
    def transition_complaint(self, complaint_id: str, to_status: str,
                             actor_id: str = "",
                             note: str = "") -> dict[str, Any] | None: ...
    def complaint_timeline(self, complaint_id: str) -> list[dict[str, Any]]: ...

    # -- batched reads for aggregate pages (same rows, fewer round trips) --
    def products_for_many(
            self, inspection_ids: list[str]) -> dict[str, list[dict[str, Any]]]: ...
    def results_for_many(
            self, inspection_ids: list[str]) -> list[dict[str, Any]]: ...
    def violations_for_many(
            self, inspection_ids: list[str]) -> list[dict[str, Any]]: ...

    # -- consumer suggestions (migration 004) --
    def create_suggestion(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def get_suggestion(self, suggestion_id: str) -> dict[str, Any] | None: ...
    def list_suggestions(self, consumer_user_id: str | None = None) -> list[dict[str, Any]]: ...
    def update_suggestion(self, suggestion_id: str, to_status: str,
                          actor_id: str = "",
                          note: str = "") -> dict[str, Any] | None: ...
    def suggestion_timeline(self, suggestion_id: str) -> list[dict[str, Any]]: ...

    # -- officer console reads --
    def violations_queue(self, filters: dict[str, Any]) -> list[dict[str, Any]]: ...
    def officer_stats(self) -> dict[str, Any]: ...
    def case_detail(self, violation_id: str) -> dict[str, Any] | None: ...
    def evidence_for(self, product_id: str) -> list[dict[str, Any]]: ...
    def record_enforcement_action(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def enforcement_for_violation(self, violation_id: str) -> list[dict[str, Any]]: ...

    # -- rule sync primitives (admin; apply path, never silent overwrite) --
    def all_rule_versions(self) -> list[dict[str, Any]]: ...
    def all_applicability(self) -> list[dict[str, Any]]: ...
    def all_weights(self, policy_id: str) -> list[dict[str, Any]]: ...
    def get_rule_by_number(self, rule_number: str) -> dict[str, Any] | None: ...
    def create_legal_rule(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def create_legal_source(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def insert_registry_entry(self, entry: dict[str, Any]) -> dict[str, Any]: ...
    def insert_rule_version(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def supersede_version(self, rule_version_id: str,
                          effective_to: str) -> dict[str, Any] | None: ...
    def insert_applicability(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def upsert_weight(self, policy_id: str, check_id: str,
                      weight: float, severity: str) -> dict[str, Any]: ...

    # -- notifications (migration 003; every row traces to a real event) --
    def create_notification(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def list_notifications(self, audiences: list[str]) -> list[dict[str, Any]]: ...
    def mark_notification_read(self, notification_id: str,
                               audiences: list[str]) -> dict[str, Any] | None: ...
    def mark_notifications_read(self, audiences: list[str]) -> int: ...
